name: Simple SOCKS5
on: workflow_dispatch

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y microsocks
          microsocks -p 1080 &
          sleep 2
          curl -L -o bore https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-x86_64-unknown-linux-musl
          chmod +x bore
          echo "Use this in Telegram:"
          ./bore local 1080 --to bore.pub
